CREATE TABLE IF NOT EXISTS variant_groups (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS asins (
  id INT AUTO_INCREMENT PRIMARY KEY,
  variant_id INT NOT NULL,
  asin VARCHAR(20) NOT NULL,
  status VARCHAR(50) DEFAULT 'normal',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (variant_id) REFERENCES variant_groups(id) ON DELETE CASCADE
);
